import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-titan-level-calculator',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './titan-level-calculator.component.html',
  styleUrl: './titan-level-calculator.component.scss',
})
export class TitanLevelCalculatorComponent {
  levelsToUp = 0;

  TitanList = [
    {
      name: 'Araji',
      image: '../assets/titan-images/Araji.jpg',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Hyperion',
      image: '../assets/titan-images/Hyperion.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Eden',
      image: '../assets/titan-images/Eden.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Solaris',
      image: '../assets/titan-images/Solaris.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Tenebris',
      image: '../assets/titan-images/Tenebris.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Moloch',
      image: '../assets/titan-images/Moloch.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Sigurd',
      image: '../assets/titan-images/Sigurd.jpg',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Angus',
      image: '../assets/titan-images/Angus.jpg',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Brustar',
      image: '../assets/titan-images/Brustar.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Rigel',
      image: '../assets/titan-images/Rigel.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Vulcan',
      image: '../assets/titan-images/Vulcan.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Nova',
      image: '../assets/titan-images/Nova.jpg',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Silva',
      image: '../assets/titan-images/Silva.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Keros',
      image: '../assets/titan-images/Keros.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Amon',
      image: '../assets/titan-images/Amon.jpg',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Ignis',
      image: '../assets/titan-images/Ignis.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Mairi',
      image: '../assets/titan-images/Mairi.jpg',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Avalon',
      image: '../assets/titan-images/Avalon.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Mort',
      image: '../assets/titan-images/Mort.png',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
    {
      name: 'Iyari',
      image: '../assets/titan-images/Iyari.jpg',
      currentLevel: 1,
      timesToLevelUp: 0,
      cost: 0,
      selected: true,
    },
  ];
}
